### Test Root Endpoint
GET http://localhost:3000/

### Test GET All Contacts
GET http://localhost:3000/contacts

### Test GET Single Contact by Path ID
GET http://localhost:3000/contacts/6a02e1e1429e7a83cdabc114

### Test GET Single Contact by Query Parameter
GET http://localhost:3000/contacts?id=6a02e1e1429e7a83cdabc114
